/*

 PLAYER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PlayerBank 0

/* Super Gameboy palette 0 */
#define PlayerSGBPal0c0 6076
#define PlayerSGBPal0c1 8935
#define PlayerSGBPal0c2 6596
#define PlayerSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerSGBPal1c0 6076
#define PlayerSGBPal1c1 8935
#define PlayerSGBPal1c2 6596
#define PlayerSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerSGBPal2c0 6076
#define PlayerSGBPal2c1 8935
#define PlayerSGBPal2c2 6596
#define PlayerSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerSGBPal3c0 6076
#define PlayerSGBPal3c1 8935
#define PlayerSGBPal3c2 6596
#define PlayerSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerCGBPal0c0 6076
#define PlayerCGBPal0c1 15871
#define PlayerCGBPal0c2 31
#define PlayerCGBPal0c3 15

/* Gameboy Color palette 1 */
#define PlayerCGBPal1c0 6076
#define PlayerCGBPal1c1 8935
#define PlayerCGBPal1c2 6596
#define PlayerCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PlayerCGBPal2c0 6076
#define PlayerCGBPal2c1 8935
#define PlayerCGBPal2c2 6596
#define PlayerCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PlayerCGBPal3c0 6076
#define PlayerCGBPal3c1 8935
#define PlayerCGBPal3c2 6596
#define PlayerCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerCGBPal4c0 6076
#define PlayerCGBPal4c1 8935
#define PlayerCGBPal4c2 6596
#define PlayerCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerCGBPal5c0 6076
#define PlayerCGBPal5c1 8935
#define PlayerCGBPal5c2 6596
#define PlayerCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerCGBPal6c0 6076
#define PlayerCGBPal6c1 8935
#define PlayerCGBPal6c2 6596
#define PlayerCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerCGBPal7c0 6076
#define PlayerCGBPal7c1 8935
#define PlayerCGBPal7c2 6596
#define PlayerCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char PlayerCGB[];
/* Start of tile array. */
extern unsigned char Player[];

/* End of PLAYER.H */
