/*

 PLAYER.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char PlayerCGB[] =
{
  0x00
};
/* Start of tile array. */
unsigned char Player[] =
{
  0x7E,0x7E,0x87,0xF9,0xA7,0xFD,0x81,0xFF,
  0x81,0xFF,0xBD,0xFF,0x81,0xFF,0x7E,0x7E
};

/* End of PLAYER.C */
